name: API Testing

on:
  workflow_dispatch:

jobs:
  testAPI:
    runs-on: ubuntu-latest
    steps:
    # Install Node on the runner
    - name: Install Node
      uses: actions/setup-node@v4
    # Install Newman
    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
    # Create directory for tests results
    - name: Create Results Directory
      run: mkdir -p testsResults
    # Run tests
    - name: Run tests
      run: |
        pwd
        newman run test-collection.json -e test-environment.json
      
  
