name: API Testing

on:
  workflow_dispatch:

jobs:
  testAPI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Install Node on the runner
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    # Install Newman
    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
    # Create directory for tests results
    - name: Create Results Directory
      run: mkdir -p testsResults
    # Run tests
    - name: Run tests
      run: |
        pwd
        newman run postman/test-collection.json -e postman/test-environment.json -r htmlextra --reporter-htmlextra-export testsResults/htmlreport.html --reporter-htmlextra-darkTheme > testsResults/runreport1.html
      
  
